
version: '3'
services:
  airflow_web:
    image: aktechthoughts/airflow_web
    build: .    
    restart: always
    ports: 
     - "8888:8888"
    volumes:
     - /home/abhishek/projects/docker/airflow-on-docker/dag:/opt/airflow/dags

